
name: google gemini
version: 1.0.0
schema: v1

models:
  - name: Ai agent model 
    provider: google
    model: gemini-1.5-pro-latest
    apiKey: AIzaSyAUcryao7WT8AdOaO_-g-GDAPjwBcElcL8
  - uses: ollama/qwen2.5-coder-7b
  - uses: anthropic/claude-4-sonnet
    with:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}


mcpServers:
  - uses: anthropic/memory-mcp
